name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    # necessary for windows
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cargo cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ./target
        key: test-cargo-registry
    - name: Run tests
      run: cargo test --verbose
